on:
  release:
    types:
      - published

name: release

jobs:
  readme-changelog:
    name: Publish changelog to Readme
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Publish changelog to Readme
        env:
          README_API_KEY: ${{ secrets.README_API_KEY }}
          RELEASE_TITLE: ${{ github.event.release.name }}
          RELEASE_BODY: ${{ github.event.release.body }}
        run: |
          jq -n --arg title "Java Unified SDK $RELEASE_TITLE" \
                --arg body "$RELEASE_BODY" \
                '{
                  title: $title,
                  content: {
                    body: $body
                  },
                  privacy: { view: "public" }
                }' > payload.json

          curl --location 'https://api.readme.com/v2/changelogs' \
            --header "Authorization: Bearer $README_API_KEY" \
            --header 'Content-Type: application/json' \
            --data @payload.json
